plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.graphics' ]
}

application {
    mainClass = 'fr.cpe.App'
}

dependencies {
    implementation 'com.google.inject:guice:7.0.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet') // Optional: Hides the 54 warnings
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
}
javadoc {
    options.addStringOption('Xdoclint:all,-missing', '-quiet')
}

tasks.register('openJavadoc') {
    dependsOn javadoc
    doLast {
        java.awt.Desktop.desktop.browse(file("build/docs/javadoc/index.html").toURI())
    }
}
